# Generated by Django 3.2.8 on 2021-10-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211031_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
            preserve_default=False,
        ),
    ]
